####################################################################
# SIMULATION PARAMETERS
####################################################################

STATE:
    x0: [0.0, 0.0, 0.65, 0.0, 0.0, 0.0,  # COM: px, py, pz, vx, vy, vz  (center of mass state)
         0.66, 0.227, 0.0, 0.66, -0.227, 0.0]  # COMMANDS: l0_command, thetadot_command_x, thetadot_command_y (single integrator state)

SIM:
    duration: 4.0         # simulation duration, [s]


####################################################################
# REFERENCE TRAJECTORY
####################################################################

REFERENCE:
    
    # Desire Leg states (velocities are assumed to be zero)
    r_des: 0.6          # desired leg length [m]
    theta_x_des: 0.227    # desired leg angle [rad], about x-axis, left is (+) and right is (-)
    theta_y_des: 0.0    # desired leg angle [rad], about y-axis

    # Desired COM states as knot points
    # px_des: [0.0, 1.0, 3.0, 7.0] 
    # py_des: [0.0, 0.0, 0.0, 0.0] 
    # pz_des: [0.65, 0.65, 0.65, 0.65]
    # time: [0.0, 2.0, 4.0, 6.0]
    px_des: [0.0, 1.0, 2.5, 4.5] 
    py_des: [0.0, 0.0, 0.0, 0.0] 
    pz_des: [0.65, 0.65, 0.65, 0.65]
    time: [0.0, 2.0, 4.0, 6.0]
    
    # whether or not to use dynamic gait cycle based on COM velocity
    dynamic_cycle: False  
    
    # static gait cycle parameters
    T_cycle_static: 0.8   # gait cycle period, [s] (in P2 sense)
    contact_static: 0.5   # ratio of the gait cycle where the leg is in contact with the ground
    phase_static: 0.5     # phase offset of a leg with another leg (left is 0 by convention)

    # dynamic gait cycle parameters
    v_min: 0.02     # minimum COM velocity, [m/s]
    v_max: 2.00     # maximum COM velocity, [m/s]
    T_coeffs: [0.19714, -0.44565, 0.84453]          # T_cycle quadratic fit coefficients
    c_coeffs: [-0.24241, 0.91088, -1.1632, 0.87261] # c cubic fit coefficients


####################################################################
# CONTROL PARAMETERS
####################################################################

CTRL_PARAMS:
    N_x: 80         # number of time steps
    N_u: 5          # number of control poins
    dt_x: 0.01      # time step, [s]
    K: 75           # number of rollouts
    N_elite: 10      # number of elite samples
    CEM_iters: 15    # number of CEM iterations


####################################################################
# COST PARAMETERS
####################################################################

COST:
    # Quadratic cost weights
    Q_com_diags:  [9.0, 9.0, 9.0, 0.7, 0.7, 0.8]    # COM: px, py, pz, vx, vy, vz
    Qf_com_diags: [10.0, 10.0, 10.0, 0.7, 0.7, 0.8]  # COM: px, py, pz, vx, vy, vz
    Q_leg_diags:  [8.0, 4.0, 4.0, 0.1, 0.1, 0.05]   # LEG: r, theta_x, theta_y, rdot, thetadot_x, thetadot_y
    Qf_leg_diags: [10.0, 6.0, 6.0, 0.2, 0.2, 0.1]    # LEG: r, theta_x, theta_y, rdot, thetadot_x, thetadot_y
    R_diags: [0.1, 0.1, 0.1]            # diagonal elements of the control cost matrix
    R_rate_diags: [0.01, 0.01, 0.01]       # diagonal elements of the control cost matrix

    # kineamtic limits and velocities cost
    limits_enabled: True
    pos_limits: True
    vel_limits: True
    w_pos_limits: 100.0
    w_vel_limits: 10.0

    # friction cone cost
    friction_enabled: False
    w_friction: 0.01

    # gait cycle cost
    gait_enabled: False
    w_gait: 1.0


####################################################################
# SYSTEM PARAMETERS
####################################################################

SYS_PARAMS:
    m: 35.0                 # COM mass,[kg] 
    g: 9.81                 # gravity, [m/s^2] 
    k: 7500.0               # spring stiffness, [N/m]
    b: 75.0                 # damping coeff, [Ns/m]
    l0: 0.65                # nominal rest length, [m]
    pz_offset: 0.0          # offset in z-dir, [m]
    r_min: 0.5              # min leg length, [m]
    r_max: 0.68              # max leg length, [m] (~0.72 for unitree)
    theta_x_min:  0.2         # min leg angle, x-dir [rad]
    theta_x_max:  0.8         # max leg angle, x-dir [rad]
    theta_y_min: -0.8         # min leg angle, y-dir [rad]
    theta_y_max:  0.8         # max leg angle, y-dir [rad]
    rdot_lim: 2.0           # max leg velocity [m/s]
    thetadot_lim: 6.0      # max angle velocity [rad/s]
    torque_ankle: True     # whether or not to enable the ankle torque
    torque_ankle_lim: 3    # ankle torque limit, [Nm]
    torque_ankle_kp: 125.0  # ankle torque proportional gain
    torque_ankle_kd: 10.0   # ankle torque derivative gain
    lambda_z_positive: True     # force positive z lambda at all times
    friction_coeff: 0.5     # friction coefficient
    interp: 'L'             # control interpolation method

####################################################################
# DISTRIBUTION PARAMETERS
####################################################################

DIST_PARAMS:
    mu: [0.0, 0.0, 0.0]         # initial means [l0dot_vel, thetadot_vel]
    sigma: [0.5, 1.57, 1.57]    # initial standard deviations
    epsilon: 0.008                # minimum eigenvalue for covariance matrix
    diag_cov: False             # strictly enforce diagonal covariance matrix
    seed_enabled: False         # enable random seed
    seed: 1                     # random seed
    saturate: False             # saturate the inputs

####################################################################
# THREADING (OpenMP)
####################################################################

THREADING:

    # CPU Threading
    enabled: True     # enable threading
    num_threads: 16     # number of thread to use in parallel
    nested: False      # nested parallelism


####################################################################
# INFO
####################################################################

INFO:
    verbose: False