####################################################################
# SIMULATION PARAMETERS
####################################################################

STATE:
    x0: [0.0, 0.0, 0.6, 0.0, 0.0, 0.0,  # COM: px, py, pz, vx, vy, vz  (center of mass state)
         0.6, 0.1, 0.0, 0.6, -0.1, 0.0]  # COMMANDS: l0_command, thetadot_command_x, thetadot_command_y (single integrator state)

SIM:
    duration: 4.0         # simulation duration, [s]

####################################################################
# REFERENCE TRAJECTORY
####################################################################

REFERENCE:
    
    # Desire Leg states (velocities are assumed to be zero)
    r_des: 0.55          # desired leg length [m]
    theta_x_des: 0.05    # desired leg angle [rad], about x-axis, left is (+) and right is (-)
    theta_y_des: 0.0    # desired leg angle [rad], about y-axis

    # Desired COM states as knot points
    px_des: [0.0, 1.0] 
    py_des: [0.0, 0.0] 
    pz_des: [0.55, 0.55]
    time: [0.0, 3.0]


####################################################################
# COST PARAMETERS
####################################################################

COST:
    # Quadratic cost weights
    Q_com_diags:  [7.0, 7.0, 8.0, 0.5, 0.5, 0.7]    # COM: px, py, pz, vx, vy, vz
    Qf_com_diags: [10.0, 10.0, 9.0, 0.7, 0.7, 0.9]  # COM: px, py, pz, vx, vy, vz
    Q_leg_diags:  [8.0, 4.0, 4.0, 0.1, 0.1, 0.05]   # LEG: r, theta_x, theta_y, rdot, thetadot_x, thetadot_y
    Qf_leg_diags: [8.0, 6.0, 6.0, 0.2, 0.2, 0.1]    # LEG: r, theta_x, theta_y, rdot, thetadot_x, thetadot_y
    R_diags: [0.5, 0.5, 0.5]            # diagonal elements of the control cost matrix
    R_rate_diags: [0.05, 0.05, 0.05]       # diagonal elements of the control cost matrix

    # kineamtic limits and velocities cost
    limits_enabled: False
    w_limits: 50.0

    # friction cone cost
    friction_enabled: False
    w_friction: 5.0

####################################################################
# CONTROL PARAMETERS
####################################################################

CTRL_PARAMS:
    N_x: 80         # number of time steps
    N_u: 4          # number of control points
    dt_x: 0.01      # time step, [s]
    K: 25           # number of rollouts
    N_elite: 5      # number of elite samples
    CEM_iters: 10    # number of CEM iterations


####################################################################
# SYSTEM PARAMETERS
####################################################################

SYS_PARAMS:
    m: 35.0                 # COM mass,[kg] 
    g: 9.81                 # gravity, [m/s^2] 
    k: 7500.0               # spring stiffness, [N/m]
    b: 75.0                 # damping coeff, [Ns/m]
    l0: 0.65                # nominal rest length, [m]
    r_min: 0.5              # min leg length, [m]
    r_max: 0.65              # max leg length, [m]
    theta_x_min:  0.1         # min leg angle, x-dir [rad]
    theta_x_max:  1.0         # max leg angle, x-dir [rad]
    theta_y_min: -1.0         # min leg angle, y-dir [rad]
    theta_y_max:  1.0         # max leg angle, y-dir [rad]
    rdot_lim: 1.0           # max leg velocity [m/s]
    thetadot_lim: 3.14      # max angle velocity [rad/s]
    torque_ankle: True     # whether or not to enable the ankle torque # TODO: think about how having torque on both legs when both are in stance
    torque_ankle_lim: 3    # ankle torque limit, [Nm]
    torque_ankle_kp: 125.0  # ankle torque proportional gain
    torque_ankle_kd: 10.0   # ankle torque derivative gain
    friction_coeff: 0.8     # friction coefficient
    interp: 'L'             # control interpolation method

####################################################################
# DISTRIBUTION PARAMETERS
####################################################################

DIST_PARAMS:
    mu: [0.0, 0.0, 0.0]         # initial means [l0dot_vel, thetadot_vel]
    sigma: [0.5, 1.57, 1.57]    # initial standard deviations
    epsilon: 0.01                # minimum eigenvalue for covariance matrix
    diag_cov: False             # strictly enforce diagonal covariance matrix
    seed_enabled: False         # enable random seed
    seed: 1                     # random seed

####################################################################
# THREADING (OpenMP)
####################################################################

THREADING:

    # CPU Threading
    enabled: True     # enable threading
    num_threads: 16     # number of thread to use in parallel
    nested: False      # nested parallelism


####################################################################
# INFO
####################################################################

INFO:
    verbose: False