####################################################################
# Sytem Parameters
####################################################################

SYS_PARAMS:
    m: 35.0                 # COM mass,[kg] 
    g: 9.81                 # gravity, [m/s^2] 
    k: 7500.0               # spring stiffness, [N/m]
    b: 50.0                 # damping coeff, [Ns/m]
    l0: 0.65                # nominal rest length, [m]
    r_min: 0.4              # min leg length, [m]
    r_max: 0.8              # max leg length, [m]
    theta_min: -1.0         # min leg angle, [rad]
    theta_max: 1.0          # max leg angle, [rad]
    rdot_lim: 1.0           # max leg velocity [m/s]
    thetadot_lim: 3.14      # max angle velocity [rad/s]
    torque_ankle: False      # whether or not to enable the ankle torque # TODO: think about how having torque on both legs when both are in stance
    torque_ankle_lim: 1   # ankle torque limit, [Nm]
    torque_ankle_kp: 125.0  # ankle torque proportional gain
    torque_ankle_kd: 10.0   # ankle torque derivative gain
    interp: 'L'             # control interpolation method


####################################################################
# Controller Parameters
####################################################################

CTRL_PARAMS:
    N: 150                              # number of time steps
    dt: 0.01                            # time step, [s]
    K: 7500                             # number of rollouts
    Nu: 40                               # number of control points
    N_elite: 500                        # number of elite samples
    CEM_iters: 25                       # number of CEM iterations


####################################################################
# Distribution Parameters
####################################################################

DIST_PARAMS:
    mu: [0.1, 0.2]              # initial means [l0dot_vel, thetadot_vel]
    sigma: [1.0, 3.14]          # initial standard deviations
    diag_cov: False             # strictly enforce diagonal covariance matrix
    epsilon: 0.0001             # small value to add to ill posed covariance matrix eigs
    seed_enabled: False         # enable random seed
    seed: 1                     # random seed


####################################################################
# INITIAL STATE and DESIRED STATE
####################################################################

STATE:
    x0: [0.0, 0.7, 0.0, 0.0,    # COM: px, pz, vx, vz  (center of mass state)
         0.6, 0.3, 0.6, -0.3]  # COMMANDS: l0_command, thetadot_command (single integrator state)


####################################################################
# COST PARAMETERS
####################################################################

COST:
    # Quadratic cost weights
    Q_com_diags:  [0.0, 3.0, 2.0, 0.05] # COM: px, pz, vx, vz
    Q_leg_diags:  [10.0, 5.0, 1.5, 1.5] # LEG: r, theta, rdot, thetadot
    Qf_com_diags: [0.0, 4.0, 3.0, 0.10] # COM: px, pz, vx, vz
    Qf_leg_diags: [11.0, 6.0, 2.0, 2.0] # LEG: r, theta, rdot, thetadot
    R_diags: [2.0, 2.0]                 # diagonal elements of the control cost matrix

    # Desired states
    pz_des: 0.6              # desired z-position [m]
    vx_des: 1.5              # desired velocity [m/s]
    r_des: 0.6               # desired leg length [m]
    theta_des: 0.2          # desired leg angle [m]

