####################################################################
# SIMULATION PARAMETERS
####################################################################

STATE:
    x0: [0.0, 0.6, 0.0, 0.0,  # COM: px, pz, vx, vz  (center of mass state)
         0.6, 0.1, 0.6, -0.1]  # COMMANDS: l0_command, thetadot_command (single integrator state)

SIM:
    duration: 4.0         # simulation duration, [s]

####################################################################
# REFERENCE TRAJECTORY
####################################################################

REFERENCE:
    
    # Desire Leg states
    r_des: 0.6          # desired leg length [m]
    theta_des: 0.0      # desired leg angle [m]

    pz_des_: 0.6       # desired COM height [m]
    vx_des_: 0.0

    # Desired COM states as knot points
    px_des: [0.0, 1.0] 
    pz_des: [0.55, 0.55]
    time: [0.0, 3.0]

    # px_des: [0.0, -0.5, -1.5, -3.0, -5.0]
    # pz_des: [0.5, 0.5, 0.5, 0.5, 0.5]
    # time:   [0.0, 1.0, 2.0, 3.0, 4.0]

    # giat cycle params
    gait_enabled: False # whether or not to enable gait cycle tracking
    T_cycle: 0.8        # gait cycle period total [s]
    T_SSP: 0.5          # single support phase duration [s]


####################################################################
# COST PARAMETERS
####################################################################

COST:
    # Quadratic cost weights
    Q_com_diags:  [7.0, 8.0, 0.5, 0.7]   # COM: px, pz, vx, vz
    Qf_com_diags: [10.0, 9.0, 0.7, 0.9]   # COM: px, pz, vx, vz
    Q_leg_diags:  [6.0, 4.0, 0.1, 0.05]  # LEG: r, theta, rdot, thetadot
    Qf_leg_diags: [8.0, 6.0, 0.5, 0.1]  # LEG: r, theta, rdot, thetadot
    R_diags: [1.0, 1.0]                # diagonal elements of the control cost matrix    
    R_rate_diags: [0.1, 0.1]         # diagonal elements of the control cost matrix    

    # gait cycle weight
    gait_cycle_weight: 0

    # log barriers (weights > 0)
    log_barrier_enabled: False
    r_weight: 1.5      
    rdot_weight: 1.5      
    theta_weight: 1.5  
    thetadot_weight: 1.5
    J_max: 1E3

####################################################################
# CONTROL PARAMETERS
####################################################################

CTRL_PARAMS:
    N_x: 80          # number of time steps
    N_u: 5          # number of control points
    dt_x: 0.01       # time step, [s]
    K: 50          # number of rollouts
    N_elite: 5     # number of elite samples
    CEM_iters: 5     # number of CEM iterations


####################################################################
# SYSTEM PARAMETERS
####################################################################

SYS_PARAMS:
    m: 35.0                 # COM mass,[kg] 
    g: 9.81                 # gravity, [m/s^2] 
    k: 7500.0               # spring stiffness, [N/m]
    b: 75.0                 # damping coeff, [Ns/m]
    l0: 0.65                # nominal rest length, [m]
    r_min: 0.4              # min leg length, [m]
    r_max: 0.8              # max leg length, [m]
    theta_min: -1.0         # min leg angle, [rad]
    theta_max: 1.0          # max leg angle, [rad]
    rdot_lim: 1.0           # max leg velocity [m/s]
    thetadot_lim: 3.14      # max angle velocity [rad/s]
    torque_ankle: True     # whether or not to enable the ankle torque # TODO: think about how having torque on both legs when both are in stance
    torque_ankle_lim: 3    # ankle torque limit, [Nm]
    torque_ankle_kp: 125.0  # ankle torque proportional gain
    torque_ankle_kd: 10.0   # ankle torque derivative gain
    interp: 'L'             # control interpolation method


####################################################################
# DISTRIBUTION PARAMETERS
####################################################################

DIST_PARAMS:
    mu: [0.0, 0.0]              # initial means [l0dot_vel, thetadot_vel]
    sigma: [0.001, 0.001]          # initial standard deviations
    diag_cov: False             # strictly enforce diagonal covariance matrix
    epsilon: 0.001               # minimum eigenvalue for covariance matrix
    seed_enabled: False         # enable random seed
    seed: 1                     # random seed

####################################################################
# THREADING (OpenMP)
####################################################################

THREADING:

    # CPU Threading
    enabled: True      # enable threading
    num_threads: 16    # number of thread to use in parallel
    nested: False       # nested parallelism


####################################################################
# INFO
####################################################################

INFO:
    verbose: False