####################################################################
# Sytem Parameters
####################################################################

SYS_PARAMS:
    m: 35.0                 # COM mass,[kg] 
    g: 9.81                 # gravity, [m/s^2] 
    k: 7500.0               # spring stiffness, [N/m]
    b: 50.0                 # damping coeff, [Ns/m]
    l0: 0.65                # nominal rest length, [m]
    r_min: 0.4              # min leg length, [m]
    r_max: 0.8              # max leg length, [m]
    theta_min: -1.0         # min leg angle, [rad]
    theta_max: 1.0          # max leg angle, [rad]
    rdot_lim: 1.0           # max leg velocity [m/s]
    thetadot_lim: 3.14      # max angle velocity [rad/s]
    torque_ankle: True      # whether or not to enable the ankle torque
    torque_ankle_lim: 0.5   # ankle torque limit, [Nm]
    torque_ankle_kp: 125.0  # ankle torque proportional gain
    torque_ankle_kd: 10.0   # ankle torque derivative gain
    interp: 'L'             # control interpolation method


####################################################################
# INITIAL STATE and DESIRED STATE
####################################################################

STATE:
    x0: [0.0, 0.7, 1.0, 1.0,    # COM: px, pz, vx, vz  (center of mass state)
         0.65, 0.0, 0.65, 0.0]  # COMMANDS: l0_command, thetadot_command (single integrator state)